### ISSUE TITLE
Verify that Metric filtering metrics are all valid (e.g no sub metrics)

### ISSUE THREAD

**Issue by andykellr** [observIQ/bindplane-op#273]
Some metrics were deprecated and should not be in the metric list.

For example:

```yaml
  # produced when receiver.hostmetricsreceiver.emitMetricsWithDirectionAttribute feature gate is enabled
  system.network.packets:
    enabled: true
    description: The number of packets transferred. (Deprecated)
    unit: "{packets}"
    sum:
      value_type: int
      aggregation: cumulative
      monotonic: true
    attributes: [device, direction]

  # produced when receiver.hostmetricsreceiver.emitMetricsWithoutDirectionAttribute feature gate is enabled
  system.network.packets.transmit:
    enabled: true
    description: The number of packets transmitted.
    unit: "{packets}"
    sum:
      value_type: int
      aggregation: cumulative
      monotonic: true
    attributes: [device]

  # produced when receiver.hostmetricsreceiver.emitMetricsWithoutDirectionAttribute feature gate is enabled
  system.network.packets.receive:
    enabled: true
    description: The number of packets received.
    unit: "{packets}"
    sum:
      value_type: int
      aggregation: cumulative
      monotonic: true
    attributes: [device]
```

We should remove the deprecated metrics from the filters and check all sources for similar issues.
