### ISSUE TITLE
Server Init results outputs extra serverURL field

### ISSUE THREAD

**Issue by jsirianni** [observIQ/bindplane-op#65]
**Describe the bug**

BindPlane is working fine. This bug is cosmetic only as server.serverURL is not currently used.

When running `sudo bindplane init server --config /etc/bindplane/config.yaml` I get two serverURL paramters.

```
host: 0.0.0.0
port: "3001"
serverURL: https://myhost:3001
username: myuser
password: mypass
logFilePath: /var/log/bindplane/bindplane.log
server:
    storageFilePath: /var/lib/bindplane/storage/bindplane.db
    secretKey: redacted
    remoteURL: wss://myhost:3001
    downloadsFolderPath: /var/lib/bindplane/downloads
    sessionsSecret: redacted
    serverURL: http://127.0.0.1:3001
```

**Steps to reproduce**

Run `init server` and provide values for server url and remote url. The resulting configuration will have an extra `server.serveURL` parameter with the default value `http://127.0.0.1:3001`.

**What did you expect to see?**

I expect to see this value once, or with the correct value.

**What did you see instead?**

serverURL exists twice with mismatched values.

**What version did you use?**

BindPlane v0.5.0

**What config did you use?**

See above.

**Environment**

GCP Debian 11
